### ISSUE TITLE
packaging not-working on latest JRuby

### ISSUE THREAD

**Issue by kares** [killbill/killbill-plugin-framework-ruby#21]
**1.7.19** at the time being ... reproduced on https://github.com/killbill/killbill-hello-world-ruby-plugin : 

```
NoMethodError: undefined method `pos' for #<Pathname:0x28cc85a8>
/opt/local/rvm/gems/jruby-1.7.19@kb/gems/killbill-3.1.12/lib/killbill/rake_task.rb:223:in `do_install_gem'
/opt/local/rvm/gems/jruby-1.7.19@kb/gems/killbill-3.1.12/lib/killbill/rake_task.rb:218:in `stage_dependencies'
/opt/local/rvm/gems/jruby-1.7.19@kb/gems/killbill-3.1.12/lib/killbill/rake_task.rb:209:in `stage_dependencies'
/opt/local/rvm/gems/jruby-1.7.19@kb/gems/killbill-3.1.12/lib/killbill/rake_task.rb:83:in `install'
/opt/local/rvm/gems/jruby-1.7.19@kb/bin/jruby_executable_hooks:15:in `(root)'
Tasks: TOP => killbill:package => killbill:stage
```

probably related to RubyGems being updated in more recent (than 1.7.16) JRuby releases

... mostly affects new comers as they try things packaging things up on their own

http://stackoverflow.com/questions/28490020/how-to-package-the-killbill-hello-world-plugin

**Comment by pierre** [comment]
Interesting... Do you know if your patch from https://github.com/killbill/killbill-plugin-framework-ruby/pull/12 fixes it (it's still on my TODO list to test it on my setup and merge it, but I didn't have a chance to do it yet)?

**Comment by kares** [comment]
no it does not, same failure as above : 
```
NoMethodError: undefined method `pos' for #<Pathname:0x7b4df922>
/opt/local/rvm/gems/jruby-1.7.19@kb/gems/killbill-3.1.12.0/lib/killbill/rake_task.rb:244:in `do_install_gem'
/opt/local/rvm/gems/jruby-1.7.19@kb/gems/killbill-3.1.12.0/lib/killbill/rake_task.rb:239:in `stage_dependencies'
/opt/local/rvm/gems/jruby-1.7.19@kb/gems/killbill-3.1.12.0/lib/killbill/rake_task.rb:230:in `stage_dependencies'
/opt/local/rvm/gems/jruby-1.7.19@kb/gems/killbill-3.1.12.0/lib/killbill/rake_task.rb:83:in `install'
/opt/local/rvm/gems/jruby-1.7.19@kb/bin/jruby_executable_hooks:15:in `(root)'
```
... see #22 for a fix
