### ISSUE TITLE
entitlement operations are not available

### ISSUE THREAD

**Issue by sbrossie** [killbill/killbill-plugin-framework-ruby#60]
The generation code will create the methods for the `KillbillApi` classes, but will not do it interface that also export operations (e.g `Entitlement`). As a result those are generated as pure POJO and  such operations are not available to plugins.

**Comment by sbrossie** [comment]
In addition to that, calling simple methods on `Entitlement` object throws exceptions:

```
 1)
/var/tmp/bundles2/plugins/ruby/killbill-stripe/4.1.0/ROOT/gems/gems/killbill-8.3.0/lib/killbill/gen/api/product.rb:96:in `to_ruby'
/var/tmp/bundles2/plugins/ruby/killbill-stripe/4.1.0/ROOT/gems/gems/killbill-8.3.0/lib/killbill/gen/api/entitlement.rb:164:in `to_ruby'
/var/tmp/bundles2/plugins/ruby/killbill-stripe/4.1.0/ROOT/gems/gems/killbill-8.3.0/lib/killbill/gen/api/entitlement_api.rb:356:in `get_all_entitlements_for_account_id'
classpath:/jruby/java/java_ext/java.util.rb:7:in `each'

```
